sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - stable
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
